apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xukus/ambulance-wl-webapi
  newName: xukus/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20260330.1148 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
- name: xukus/ambulance-ufe
  newName: xukus/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260323.1009 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: xukus/patient-visit-fe
  newName: xukus/patient-visit-fe # {"$imagepolicy":  "wac-hospital:patient-visit-fe:name"}
  newTag: main.20260508.1445 # {"$imagepolicy": "wac-hospital:patient-visit-fe:tag"}
